-- DuckDB schema — matches the CSV files generated by scripts/generate_data.py
-- Applied automatically by the bootstrap pipeline on first run.

CREATE TABLE IF NOT EXISTS movies (
    movie_id                INTEGER PRIMARY KEY,
    title                   VARCHAR   NOT NULL,
    genre                   VARCHAR   NOT NULL,
    release_date            DATE,
    budget_usd              BIGINT,
    box_office_usd          BIGINT,
    rating                  DOUBLE    CHECK (rating >= 0 AND rating <= 5),
    director                VARCHAR,
    release_year            INTEGER,
    runtime_mins            INTEGER,
    streaming_release_date  DATE,
    status                  VARCHAR
);

CREATE TABLE IF NOT EXISTS viewers (
    viewer_id          INTEGER PRIMARY KEY,
    age                INTEGER,
    gender             VARCHAR,
    city               VARCHAR,
    country            VARCHAR,
    subscription_tier  VARCHAR,
    preferred_genre    VARCHAR,
    join_date          DATE
);

CREATE TABLE IF NOT EXISTS watch_activity (
    activity_id           INTEGER PRIMARY KEY,
    viewer_id             INTEGER,
    movie_id              INTEGER,
    watch_date            DATE,
    watch_duration_mins   INTEGER,
    completion_rate       DOUBLE,
    device_type           VARCHAR
);

CREATE TABLE IF NOT EXISTS reviews (
    review_id    INTEGER PRIMARY KEY,
    viewer_id    INTEGER,
    movie_id     INTEGER,
    rating       DOUBLE    CHECK (rating >= 0 AND rating <= 5),
    sentiment    VARCHAR,
    review_text  VARCHAR,
    review_date  DATE
);

CREATE TABLE IF NOT EXISTS marketing_spend (
    spend_id        INTEGER PRIMARY KEY,
    movie_id        INTEGER,
    title           VARCHAR,
    channel         VARCHAR,
    spend_usd       BIGINT,
    impressions     BIGINT,
    clicks          BIGINT,
    campaign_start  DATE,
    campaign_end    DATE
);

CREATE TABLE IF NOT EXISTS regional_performance (
    region_id             INTEGER PRIMARY KEY,
    movie_id              INTEGER,
    title                 VARCHAR,
    city                  VARCHAR,
    country               VARCHAR,
    month                 VARCHAR,
    views                 BIGINT,
    revenue_usd           BIGINT,
    engagement_score      DOUBLE,
    avg_watch_time_mins   DOUBLE
);
