"""
Pydantic validation models for each CSV-backed table.
Column names match the CSV files generated by scripts/generate_data.py.
"""

from __future__ import annotations

from datetime import date
from typing import Optional

from pydantic import BaseModel, Field, field_validator


def _to_int(v):
    if v == "" or v is None:
        return None
    return int(float(str(v).replace(",", "").replace("$", "").strip()))


def _to_float(v):
    if v == "" or v is None:
        return None
    return float(str(v).strip())


class Movie(BaseModel):
    movie_id:               Optional[int]   = None
    title:                  str
    genre:                  str
    release_date:           Optional[date]  = None
    budget_usd:             Optional[int]   = None
    box_office_usd:         Optional[int]   = None
    rating:                 Optional[float] = Field(None, ge=0, le=5)
    director:               Optional[str]   = None
    release_year:           Optional[int]   = None
    runtime_mins:           Optional[int]   = None
    streaming_release_date: Optional[date]  = None
    status:                 Optional[str]   = None

    _ci = field_validator("movie_id", "budget_usd", "box_office_usd",
                          "release_year", "runtime_mins", mode="before")(classmethod(_to_int))
    _cf = field_validator("rating", mode="before")(classmethod(_to_float))


class Viewer(BaseModel):
    viewer_id:         Optional[int]  = None
    age:               Optional[int]  = None
    gender:            Optional[str]  = None
    city:              Optional[str]  = None
    country:           Optional[str]  = None
    subscription_tier: Optional[str]  = None
    preferred_genre:   Optional[str]  = None
    join_date:         Optional[date] = None

    _ci = field_validator("viewer_id", "age", mode="before")(classmethod(_to_int))


class WatchActivity(BaseModel):
    activity_id:          Optional[int]   = None
    viewer_id:            Optional[int]   = None
    movie_id:             Optional[int]   = None
    watch_date:           Optional[date]  = None
    watch_duration_mins:  Optional[int]   = None
    completion_rate:      Optional[float] = Field(None, ge=0, le=1)
    device_type:          Optional[str]   = None

    _ci = field_validator("activity_id", "viewer_id", "movie_id",
                          "watch_duration_mins", mode="before")(classmethod(_to_int))
    _cf = field_validator("completion_rate", mode="before")(classmethod(_to_float))


class Review(BaseModel):
    review_id:   Optional[int]   = None
    viewer_id:   Optional[int]   = None
    movie_id:    Optional[int]   = None
    rating:      Optional[float] = Field(None, ge=0, le=5)
    sentiment:   Optional[str]   = None
    review_text: Optional[str]   = None
    review_date: Optional[date]  = None

    _ci = field_validator("review_id", "viewer_id", "movie_id", mode="before")(classmethod(_to_int))
    _cf = field_validator("rating", mode="before")(classmethod(_to_float))


class MarketingSpend(BaseModel):
    spend_id:       Optional[int]  = None
    movie_id:       Optional[int]  = None
    title:          Optional[str]  = None
    channel:        Optional[str]  = None
    spend_usd:      Optional[int]  = None
    impressions:    Optional[int]  = None
    clicks:         Optional[int]  = None
    campaign_start: Optional[date] = None
    campaign_end:   Optional[date] = None

    _ci = field_validator("spend_id", "movie_id", "spend_usd",
                          "impressions", "clicks", mode="before")(classmethod(_to_int))


class RegionalPerformance(BaseModel):
    region_id:           Optional[int]   = None
    movie_id:            Optional[int]   = None
    title:               Optional[str]   = None
    city:                Optional[str]   = None
    country:             Optional[str]   = None
    month:               Optional[str]   = None
    views:               Optional[int]   = None
    revenue_usd:         Optional[int]   = None
    engagement_score:    Optional[float] = None
    avg_watch_time_mins: Optional[float] = None

    _ci = field_validator("region_id", "movie_id", "views",
                          "revenue_usd", mode="before")(classmethod(_to_int))
    _cf = field_validator("engagement_score", "avg_watch_time_mins", mode="before")(classmethod(_to_float))


# Maps table name → (model class, ordered column list for INSERT).
CSV_MODEL_MAP: dict[str, tuple] = {
    "movies": (Movie, [
        "movie_id", "title", "genre", "release_date",
        "budget_usd", "box_office_usd", "rating", "director",
        "release_year", "runtime_mins", "streaming_release_date", "status",
    ]),
    "viewers": (Viewer, [
        "viewer_id", "age", "gender", "city", "country",
        "subscription_tier", "preferred_genre", "join_date",
    ]),
    "watch_activity": (WatchActivity, [
        "activity_id", "viewer_id", "movie_id", "watch_date",
        "watch_duration_mins", "completion_rate", "device_type",
    ]),
    "reviews": (Review, [
        "review_id", "viewer_id", "movie_id", "rating",
        "sentiment", "review_text", "review_date",
    ]),
    "marketing_spend": (MarketingSpend, [
        "spend_id", "movie_id", "title", "channel", "spend_usd",
        "impressions", "clicks", "campaign_start", "campaign_end",
    ]),
    "regional_performance": (RegionalPerformance, [
        "region_id", "movie_id", "title", "city", "country",
        "month", "views", "revenue_usd", "engagement_score", "avg_watch_time_mins",
    ]),
}
