"""
SQL Guard – validates LLM-generated SQL before execution.

Defence layers (applied in order):
  1. sqlglot parsing — rejects strings that are not valid SQL.
  2. Statement type allowlist — only SELECT is permitted.
  3. Table allowlist — only tables in the schema are queryable.
  4. Banned keyword blocklist — hard blocks for DDL and DML.
  5. Comment stripping — removes inline comments that obscure intent.

If any layer fails, SQLGuardError is raised with a safe message.
The raw failing SQL is logged at DEBUG level — never returned to the user.
"""

from __future__ import annotations

import logging
import re

import sqlglot
import sqlglot.expressions as exp

logger = logging.getLogger(__name__)


class SQLGuardError(ValueError):
    """Raised when generated SQL fails validation."""


# ── Configuration ──────────────────────────────────────────────────────────────

ALLOWED_TABLES = frozenset({
    "movies",
    "viewers",
    "watch_activity",
    "reviews",
    "marketing_spend",
    "regional_performance",
    "document_chunks",
})

BANNED_KEYWORDS = frozenset({
    "DROP", "DELETE", "INSERT", "UPDATE", "ALTER", "CREATE",
    "TRUNCATE", "EXEC", "EXECUTE", "GRANT", "REVOKE",
    "COPY", "VACUUM", "ANALYZE", "EXPLAIN",
    "SET",       # could change RLS session variable
    "RESET",
    "LOAD",
    "INSTALL",
})


# ── Helpers ────────────────────────────────────────────────────────────────────

def _strip_comments(sql: str) -> str:
    """Remove -- line comments and /* block comments */."""
    sql = re.sub(r"--[^\n]*", "", sql)
    sql = re.sub(r"/\*.*?\*/", "", sql, flags=re.DOTALL)
    return sql.strip()


def _extract_statement_type(parsed) -> str:
    """Return the top-level statement type string from a sqlglot AST."""
    return type(parsed).__name__.upper()


def _extract_table_names(parsed) -> set[str]:
    """Walk the AST and collect all referenced table names (lower-cased)."""
    return {
        table.name.lower()
        for table in parsed.find_all(exp.Table)
        if table.name
    }


# ── Public API ─────────────────────────────────────────────────────────────────

def sql_guard(raw_sql: str) -> str:
    """
    Validate and clean a SQL string generated by the LLM.

    Args:
        raw_sql: The SQL string returned by the LLM (may contain markdown
                 fences, extra whitespace, or comments).

    Returns:
        A clean, validated SQL string ready for execution.

    Raises:
        SQLGuardError: if any validation layer fails.
    """
    if not raw_sql or not raw_sql.strip():
        raise SQLGuardError("LLM returned an empty SQL string")

    # Strip markdown code fences that LLMs often add
    sql = re.sub(r"```sql|```", "", raw_sql, flags=re.IGNORECASE).strip()

    # Layer 1: comment stripping
    sql = _strip_comments(sql)

    # Layer 2: banned keyword check (before parsing — catches obfuscated attempts)
    tokens_upper = set(re.findall(r"\b\w+\b", sql.upper()))
    blocked = tokens_upper & BANNED_KEYWORDS
    if blocked:
        logger.debug("SQL guard blocked keywords: %s | SQL: %s", blocked, sql)
        raise SQLGuardError(
            f"Generated SQL contains disallowed keywords: {blocked}"
        )

    # Layer 3: sqlglot parsing
    try:
        statements = sqlglot.parse(sql)
    except Exception as exc:
        logger.debug("sqlglot parse error: %s | SQL: %s", exc, sql)
        raise SQLGuardError("Generated SQL could not be parsed") from exc

    if not statements or len(statements) > 1:
        raise SQLGuardError(
            "Expected exactly one SQL statement; got multiple or none"
        )

    parsed = statements[0]

    # Layer 4: statement type allowlist — SELECT and UNION (combined SELECTs)
    stmt_type = _extract_statement_type(parsed)
    if stmt_type not in ("SELECT", "UNION"):
        logger.debug(
            "SQL guard blocked statement type: %s | SQL: %s", stmt_type, sql
        )
        raise SQLGuardError(
            f"Only SELECT statements are allowed; got {stmt_type}"
        )

    # Layer 5: table allowlist
    referenced_tables = _extract_table_names(parsed)
    unknown = referenced_tables - ALLOWED_TABLES
    if unknown:
        logger.debug(
            "SQL guard blocked unknown tables: %s | SQL: %s", unknown, sql
        )
        raise SQLGuardError(f"Query references unknown tables: {unknown}")

    # Return the cleaned, normalised SQL (not the raw LLM string)
    return sql